@startuml
Participant -> "ACM Runtime": [ASYNC] Deregister
"ACM Runtime" -> "ACM Database": Set Participant State as OFF_LINE
Participant <- "ACM Runtime": [ASYNC] Deregistration Accepted
Participant -> Participant: Shutdown Participant
@enduml
