@startuml
activate Participant
  Participant -> "CLAMP Runtime": [ASYNC] Register
activate "CLAMP Runtime"
deactivate Participant
  "CLAMP Runtime" -> "CLAMP Database": Create or Update Perticipant Registration,\n store supported ACM element types \n and set Perticipant State as ON_LINE
  "CLAMP Runtime" -> Participant: [ASYNC] Registration Accepted
  loop over ACM Definition
	  "CLAMP Runtime" -> "CLAMP Database": Mark all ACM element instances deployed\n on Participant as Restarting
    "CLAMP Runtime" -> Participant: [ASYNC] Restart\n send Common Property Values\n and Instance Elements of this Participant]
deactivate "CLAMP Runtime"
activate Participant
Participant -> Participant: Store Common Property Values and Instance Elements
Participant -> "CLAMP Runtime": [ASYNC] State Change Ack
activate "CLAMP Runtime"
deactivate Participant
  "CLAMP Runtime" -> "CLAMP Database": Remove Restarting from all Compositions \n and Instances of this Participant
deactivate "CLAMP Runtime"
  end
@enduml
