@startuml

participant Participant
participant "ACM Runtime"
database "ACM Database"

activate Participant
  Participant -> "ACM Runtime": [ASYNC] Register
activate "ACM Runtime"
deactivate Participant
  "ACM Runtime" -> "ACM Database": Create a Participant Replica Registration,\n store supported ACM element types \n and set Replica State as ON_LINE
  loop ACM Definition
    "ACM Runtime" -> Participant: [ASYNC] Sync message\n send Common Property Values\n and Instance Elements of this Participant
activate Participant
    Participant -> Participant: Store Common Property Values and Instance Elements
  end loop
  alt
  "ACM Runtime" -> Participant: [ASYNC] Registration Accepted
deactivate "ACM Runtime"
Participant -> Participant:  set participant as registered
Participant -> "ACM Runtime": [ASYNC] Status message
deactivate Participant
end
@enduml
