@startuml

title Policy Type Design

participant PolicyTypeDesignClient <<API_User >>
box "PolicyDesign" #LightBlue
  participant PolicyTypeDesign
end box
autonumber

PolicyTypeDesignClient --> PolicyTypeDesign : Get Policy Type Reference and Metadata
PolicyTypeDesign --> PolicyDB : Get Policy Type Metadata\nand Artifact

alt Policy Type Artifact exists
  PolicyTypeDesign --> DCAE_DS : Return Policy Type Reference and Metadata
else Policy Artifact does not exist
  PolicyTypeDesign --> DCAE_DS : Return New Policy Type Reference and Empty Metadata
end

PolicyTypeDesignClient --> PolicyTypeDesignClient : Policy Type Editing and Generation Session

activate PolicyTypeDesignClient
deactivate PolicyTypeDesignClient

PolicyTypeDesignClient --> PolicyTypeDesign : Create Policy Type and Metadata
PolicyTypeDesign --> PolicyTypeDesignClient : Policy Generation Result

@enduml