@startuml

title Scripted Policy Design

participant Script <<API_User >>
collections DirectiveFile

box "PolicyDesign" #LightBlue
  participant PolicyTypeDesign
  participant PolicyDesign
end box

autonumber

activate Script

loop
  Script --> DirectiveFile : Read next directive from script file
  Script --> PolicyTypeDesign : Read Policy Type for directive
  Script --> Script : Prepare TOSCA Policy for coreation
  Script --> Script : Read parameters from script file directive
  Script --> Script : Set Parameters in TOSCA Policy being prepared
  Script --> PolicyDesign : Create Policy
  PolicyDesign --> Script : Policy creation result
end

deactivate Script

@enduml