@startuml

title Scripted Policy Design

participant Script <<API_User >>

box "PolicyDesign" #LightBlue
  participant PolicyTypeDesign
  participant PolicyDesign
end box

autonumber

activate Script

loop
  Script --> PolicyTypeDesign : Read Policy Type using command
  Script --> Script : Prepare TOSCA Policy for creation
  Script --> Script : Parse parameters from retrieved policy type
  Script --> Script : Set Parameters in TOSCA Policy being prepared
  Script --> PolicyDesign : Create Policy using command
  PolicyDesign --> Script : Policy creation result
end

deactivate Script

@enduml