@startuml
participant ACM_Runtime
participant Participant

ACM_Runtime -> Participant: [ASYNC] Deprime AC Element Types for this AC Type

loop over AC Element Types in AC Type
 alt Does the deprimed Participant ID on this AC Element Type\nmatch my Participant ID
  alt Does this AC Element Type Exist
   Participant -> Participant: Delete AC Element Type
   activate Participant
   deactivate Participant
   note left of Participant
    Deletion of an AC Element Type always returns success
   end note
   ACM_Runtime <- Participant: [ASYNC] INFO: AC Element successfully primed
  else
    ACM_Runtime <- Participant: [ASYNC] WARN: AC Element Type is already deprimed
  end
 else
  note left of Participant
   ignore this AC Element Type as its for another participant
  end note
 end
end

@enduml
