@startuml

participant Participant
participant ACM_Runtime
database ACM_Database

Participant -> Participant: Uninitialize all ACM Element Instances running on Participant\n(See Instantiation Dialogues)
activate Participant
deactivate Participant

Participant -> ACM_Runtime: [ASYNC] Deregister
ACM_Runtime -> ACM_Database: Delete Participant Registration
ACM_Runtime -> ACM_Database: Set Participant State as OFFLINE
Participant <- ACM_Runtime: [ASYNC] Deregistration Accepted

ACM_Runtime -> ACM_Runtime: Mark all ACM Element Instances\nrunning on Participant as OFFLINE
activate ACM_Runtime
deactivate ACM_Runtime

@enduml
