@startuml

participant "ACM Runtime"
database "ACM Database"
participant "Participant Replica 1"
participant "Participant Replica 2"

"ACM Runtime" <- "Participant Replica 1": [ASYNC] Lock Automation Composition Element \nInstance Response
"ACM Runtime" -> "ACM Database": Store Automation Composition Element Instance \nResponse Information

alt Is AC Element Instance Locked?
 "ACM Runtime" -> "ACM Database": Set AC Element Instance administrative state as LOCKED
 alt Have all the other AC Element Instances in this AC Instance been LOCKED?
  "ACM Runtime" -> "ACM Database": Set AC Instance administrative state as LOCKED
  "ACM Runtime" -> "Participant Replica 2": [ASYNC] Send sync message
  end
end

@enduml
