@startuml
participant "ACM Runtime"
participant Participant
participant "Participant API"

"ACM Runtime" -> Participant: [ASYNC] Prepare AC Element Instances for this AC Instance

loop over AC Element Instances in AC Instance
 alt Does the primed Participant ID on this AC Element Instance\nmatch my Participant ID?
   Participant -> "Participant API": Prepare AC Element Instance
   activate "Participant API"
   Participant <- "Participant API": AC Element Instance Prepare Response
   deactivate "Participant API"
   alt AC Element Prepare completed
    Participant -> Participant: Set AC Element Instance administrative subState to NONE
    "ACM Runtime" <- Participant: [ASYNC] INFO: Prepare AC Element has been completed
   end
 else
  note left of Participant
   Ignore this AC Element instance as its for another participant
  end note
 end
end

@enduml
