@startuml
participant REST
participant ACM_Runtime
participant Participant
database ACM_Database

alt Automation Composition Type has Deployed Instances
  REST <- ACM_Runtime: Priming of Automation Composition Type Failed, instances deployed
else Automation Composition Type is in state COMMISSIONED or PRIMED
 REST -> ACM_Runtime: Prime Automation Composition Type

 ACM_Runtime -> ACM_Database: Read Automation Composition Type
 ACM_Runtime -> ACM_Database: Read Participants
 ACM_Runtime -> ACM_Runtime: Set suitable participant ID on each AC Element Type

 alt Was a sutable participant ID found for each AC Element Type?
  ACM_Runtime -> Participant: [ASYNC] Send Priming Request to all Participants\nwith Automation Composition Type Definition
  ACM_Runtime -> ACM_Database: Set Automation Composition Type State to PRIMING

  REST <- ACM_Runtime: Priming of Automation Composition Type Ordered
 else
   REST <- ACM_Runtime: Priming of Automation Composition Type Faield, no sutiable participant found
 end
else
 REST <- ACM_Runtime: Priming of Automation Composition Type Failed, invalid state
end

@enduml
