@startuml
participant "ACM Runtime"
database "ACM Database"
participant "Participant Replica 1"
participant "Participant Replica 2"

"ACM Runtime" <- "Participant Replica 1": [ASYNC] Result of Priming of AC Element Type
"ACM Runtime" -> "ACM Database": Record result of AC Element Type Priming

alt Is AC Element Type Primed?
 alt Have all the other AC Element Types in this AC Type been Primed?
  "ACM Runtime" -> "ACM Database": Set AC Type state as PRIMED
  "ACM Runtime" -> "Participant Replica 2": [ASYNC] Send sync message
  end
end

@enduml
