@startuml
participant ACM_Runtime
participant Participant
database ACM_Database

ACM_Runtime <- Participant: [ASYNC] Result of Priming of AC Element Type
ACM_Runtime -> ACM_Database: Record result of AC Element Type Priming

alt Is AC Element Type Primed?
 alt Have all the other AC Element Types in this AC Type been Primed?
  ACM_Runtime -> ACM_Runtime: Set AC Type state as PRIMED
  end
end

@enduml
