@startuml

participant Participant
participant ACM_Runtime
database ACM_Database

Participant -> ACM_Runtime: [ASYNC] Register
ACM_Runtime -> ACM_Database: Create or Update Participant Registration\nand store supported ACM element types
ACM_Runtime -> ACM_Database: Set Participant State as ONLINE
Participant <- ACM_Runtime: Registration Accepted

ACM_Runtime -> ACM_Runtime: Mark all ACM Element Instances\nrunning on Participant as ONLINE
activate ACM_Runtime
deactivate ACM_Runtime

@enduml
