@startuml

participant Participant
participant "ACM Runtime"
database "ACM Database"

loop Every Participant Supervision Interval
 Participant -> "ACM Runtime": [ASYNC] Heartbeat message including\nreplica ID and participant ID
 "ACM Runtime" -> "ACM Database": Update Participant Replica as 'ON_LINE'
end

@enduml
