@startuml

participant "ACM Runtime"
database "ACM Database"

loop Every ACM Runtime Supervision Interval
  loop Over all Participant replicas
    "ACM Runtime" -> "ACM Database": Read Participant Replica Heartbeat Information
    alt Participant Replica Heartbeat not received in Timeout Interval
      "ACM Runtime" -> "ACM Database": Set Participant Replica State as OFFLINE
    end
  end
end

@enduml
