@startuml
participant "Participant API Replica 1"
participant "Participant Replica 1"
participant "ACM Runtime"
participant "Participant Replica 2"

"Participant API Replica 1" -> "Participant API Replica 1": Perform Operation that Updates \nOperational State, Use State and outProperties
activate "Participant API Replica 1"
deactivate "Participant API Replica 1"

"Participant API Replica 1" -> "Participant Replica 1": Operational State, Use State and outProperties \nhas been updated
"Participant Replica 1" -> "Participant Replica 1": Update Operational State, Use State and outProperties \nin ACM Element Instance
"Participant Replica 1" -> "ACM Runtime": [ASYNC] Send message including states and outProperties \nof AC Element Instances on Participant
"ACM Runtime" -> "Participant Replica 2": [ASYNC] Send sync message

== Periodically with Heartbeat ==
"Participant Replica 1" -> "ACM Runtime": [ASYNC] Heartbeat message including status

@enduml
