@startuml

[*] --> UNDEPLOYED: Create
UNDEPLOYED --> [*]: Delete
UNDEPLOYED --> DEPLOYING: Deploy
DEPLOYING --> DEPLOYED: AC Instance\nElement DEPLOYED
DEPLOYING --> UNDEPLOYING: Undeploy
DEPLOYED --> UNDEPLOYING: Undeploy
DEPLOYED --> UPDATING: Update
DEPLOYED --> MIGRATING: Migrate
MIGRATING --> DEPLOYED: AC Instance\nElement MIGRATED
UNDEPLOYING --> UNDEPLOYED: AC Instance\nElement UNDEPLOYED
UNDEPLOYING --> UNDEPLOYED: AC Instance\nElement UNDEPLOYED


state DEPLOYED {
 [*] --> LOCKED: Deploy
 LOCKED --> [*]: Undeploy
 LOCKED --> UNLOCKING: Unlock
 UNLOCKING --> UNLOCKED: AC Instance\nElement UNLOCKED
 UNLOCKED --> LOCKING: Lock
 UNLOCKING --> LOCKING: Lock
 LOCKING --> LOCKED: AC Instance\nElement LOCKED
}

@enduml
