@startuml

[*] --> NONE:UNDEPLOYED
NONE:UNDEPLOYED --> PREPARING: Prepare
NONE:UNDEPLOYED --> DELETING: Delete
PREPARING --> NONE:UNDEPLOYED: Completed
PREPARING --> PREPARING:UNDEPLOYED:FAILED: Failed
PREPARING:UNDEPLOYED:FAILED --> PREPARING: Prepare
PREPARING --> PREPARING:UNDEPLOYED:TIMEOUT: Timeout
PREPARING:UNDEPLOYED:TIMEOUT --> PREPARING: Prepare
PREPARING:UNDEPLOYED:FAILED--> DELETING: Delete
PREPARING:UNDEPLOYED:TIMEOUT  --> DELETING: Delete

@enduml
