@startuml

[*] --> NONE:DEPLOYED
NONE:DEPLOYED --> MIGRATION_PRECHECKING: Migrate precheck
MIGRATION_PRECHECKING --> NONE:DEPLOYED: Completed
MIGRATION_PRECHECKING --> MIGRATION_PRECHECKING:DEPLOYED:FAILED: Failed
MIGRATION_PRECHECKING --> MIGRATION_PRECHECKING:DEPLOYED:TIMEOUT: Timeout
MIGRATION_PRECHECKING:DEPLOYED:FAILED --> MIGRATION_PRECHECKING: Migrate precheck
MIGRATION_PRECHECKING:DEPLOYED:TIMEOUT --> MIGRATION_PRECHECKING: Migrate precheck
NONE:DEPLOYED --> UNDEPLOYING: Undeploy
MIGRATION_PRECHECKING:DEPLOYED:FAILED --> UNDEPLOYING: Undeploy
MIGRATION_PRECHECKING:DEPLOYED:TIMEOUT --> UNDEPLOYING: Undeploy


@enduml
