@startuml

UNDEPLOYED --> DEPLOYING: Deploy
DEPLOYING --> DEPLOYED: AC Instance Elements\nall DEPLOYED

state UNDEPLOYED {
 NONE:UNDEPLOYED --> PREPARING: Prepare
 PREPARING --> NONE:UNDEPLOYED: Completed
}

state DEPLOYED {
 NONE:DEPLOYED --> REVIEWING: Review
 REVIEWING --> NONE:DEPLOYED: Completed
 NONE:DEPLOYED --> MIGRATION_PRECHECKING: Migrate precheck
 MIGRATION_PRECHECKING --> NONE:DEPLOYED: Completed
}

@enduml
