@startuml

DEPLOYED:DEPLOYED:NO_ERROR --> UPDATING:UPDATING: Update
UPDATING:UPDATING --> DEPLOYED:DEPLOYED:NO_ERROR: Updated
UPDATING:UPDATING --> DEPLOYED:UPDATING:FAILED: Update failed
UPDATING:UPDATING --> UPDATING:UPDATING:TIMEOUT: Update timeout
DEPLOYED:UPDATING:FAILED --> UPDATING:UPDATING: Update
DEPLOYED:UPDATING:FAILED --> UNDEPLOYING:UNDEPLOYING: Undeploy
UPDATING:UPDATING:TIMEOUT --> UPDATING:UPDATING: Update
UPDATING:UPDATING:TIMEOUT --> DEPLOYED:UPDATING:FAILED: Update failed
UPDATING:UPDATING:TIMEOUT --> UNDEPLOYING:UNDEPLOYING: Undeploy
UPDATING:UPDATING:TIMEOUT --> DEPLOYED:DEPLOYED:NO_ERROR: Updated

@enduml
