@startuml

[*] --> NONE:DEPLOYED
NONE:DEPLOYED --> REVIEWING: Review
REVIEWING --> NONE:DEPLOYED: Completed
REVIEWING --> REVIEWING:DEPLOYED:FAILED: Failed
REVIEWING --> REVIEWING:DEPLOYED:TIMEOUT: Timeout
REVIEWING:DEPLOYED:FAILED --> REVIEWING: Review
REVIEWING:DEPLOYED:TIMEOUT --> REVIEWING: Review
NONE:DEPLOYED --> UNDEPLOYING: Undeploy
REVIEWING:DEPLOYED:FAILED --> UNDEPLOYING: Undeploy
REVIEWING:DEPLOYED:TIMEOUT --> UNDEPLOYING: Undeploy

@enduml
