@startuml

DEPLOYED:DEPLOYED:NO_ERROR --> MIGRATING:MIGRATING: Migrate
MIGRATING:MIGRATING --> DEPLOYED:DEPLOYED:NO_ERROR: Migrated
MIGRATING:MIGRATING --> DEPLOYED:MIGRATING:FAILED: Migrate failed
MIGRATING:MIGRATING --> MIGRATING:MIGRATING:TIMEOUT: Migrate timeout
DEPLOYED:MIGRATING:FAILED --> UNDEPLOYING:UNDEPLOYING: Undeploy
MIGRATING:MIGRATING:TIMEOUT --> DEPLOYED:MIGRATING:FAILED: Migrate failed
MIGRATING:MIGRATING:TIMEOUT --> UNDEPLOYING:UNDEPLOYING: Undeploy
MIGRATING:MIGRATING:TIMEOUT --> DEPLOYED:DEPLOYED:NO_ERROR: Migrated

@enduml
