@startuml

UNDEPLOYED:UNDEPLOYED:NO_ERROR --> DELETING:DELETING: Delete
DELETING:DELETING --> UNDEPLOYED:DELETING:FAILED: Delete failed
DELETING:DELETING --> DELETING:DELETING:TIMEOUT
DELETING:DELETING --> [*]: Deleted
UNDEPLOYED:DELETING:FAILED --> DELETING:DELETING: Delete
DELETING:DELETING:TIMEOUT --> UNDEPLOYED:DELETING:FAILED: Delete failed
DELETING:DELETING:TIMEOUT --> DELETING:DELETING: Delete
DELETING:DELETING:TIMEOUT -->  [*]: Deleted

@enduml
