@startuml

COMMISSIONED:COMMISSIONED:NO_ERROR --> PRIMING:PRIMING: Prime

PRIMING:PRIMING --> PRIMED:PRIMED:NO_ERROR: AC Element Types\nall PRIMED
PRIMING:PRIMING --> COMMISSIONED:PRIMING:FAIL: Prime Failed
PRIMING:PRIMING --> PRIMING:PRIMING:TIMEOUT: Prime Timeout

COMMISSIONED:PRIMING:FAIL --> DEPRIMING:DEPRIMING: Deprime
COMMISSIONED:PRIMING:FAIL --> PRIMING:PRIMING: Prime Again

PRIMING:PRIMING:TIMEOUT --> DEPRIMING:DEPRIMING: Deprime
PRIMING:PRIMING:TIMEOUT --> PRIMING:PRIMING: Prime Again
PRIMING:PRIMING:TIMEOUT --> PRIMED:PRIMED:NO_ERROR: AC Element Types\nall PRIMED

DEPRIMING:DEPRIMING --> COMMISSIONED:COMMISSIONED:NO_ERROR: AC Element Types\nall DEPRIMED
DEPRIMING:DEPRIMING --> PRIMED:DEPRIMING:FAIL: Deprime Failed
DEPRIMING:DEPRIMING --> DEPRIMING:DEPRIMING:TIMEOUT: Deprime Timeout

PRIMED:DEPRIMING:FAIL --> DEPRIMING:DEPRIMING: Deprime Again
PRIMED:DEPRIMING:FAIL --> PRIMING:PRIMING: Prime

DEPRIMING:DEPRIMING:TIMEOUT --> DEPRIMING:DEPRIMING: Deprime Again
DEPRIMING:DEPRIMING:TIMEOUT --> PRIMING:PRIMING: Prime
DEPRIMING:DEPRIMING:TIMEOUT --> COMMISSIONED:COMMISSIONED:NO_ERROR: AC Element Types\nall DEPRIMED

PRIMED:PRIMED:NO_ERROR --> DEPRIMING:DEPRIMING: Deprime

@enduml
