@startuml

participant Participant
participant ACM_Runtime
database ACM_Database

loop Every Participant Supervision Interval
 Participant -> ACM_Runtime: [ASYNC] Heartbeat message including\nstatus and states of AC Element Instances on Participant
 ACM_Runtime -> ACM_Database: Update Participant Heartbeat data
 ACM_Runtime -> ACM_Database: Set Participant State as ONLINE

 loop Every AC Element Instance in Heartbeat Message
  ACM_Runtime -> ACM_Database: Mark AC Element Instance as ONLINE\nand Update AC Element Instance status
 end
end

@enduml
