spring:
  security:
    user:
      name: policyadmin
      password: zb!XztG34
  datasource:
    url: jdbc:mariadb://localhost:3306/policyadmin
    driverClassName: org.mariadb.jdbc.Driver
    username: policy_user
    password: policy_user
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy
  mvc:
    converters:
      preferred-json-mapper: gson

server:
  port: 6970
  servlet:
    context-path: /policy/pap/v1
pap:
  name: PapGroup
  topic:
    pdp-pap.name: POLICY-PDP-PAP
    notification.name: POLICY-NOTIFICATION
    heartbeat.name: POLICY-HEARTBEAT
  pdpParameters:
    heartBeatMs: 120000
    updateParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
    stateChangeParameters:
      maxRetryCount: 1
      maxWaitMs: 30000
  topicParameterGroup:
    topicSources:
      - topic: ${pap.topic.pdp-pap.name}
        servers:
          - kafka
        topicCommInfrastructure: NOOP
        fetchTimeout: 15000
      - topic: ${pap.topic.heartbeat.name}
        effectiveTopic: ${pap.topic.pdp-pap.name}
        consumerGroup: policy-pap
        servers:
          - kafka
        topicCommInfrastructure: NOOP
        fetchTimeout: 15000
    topicSinks:
      - topic: ${pap.topic.pdp-pap.name}
        servers:
          - kafka
        topicCommInfrastructure: NOOP
      - topic: ${pap.topic.notification.name}
        servers:
          - kafka
        topicCommInfrastructure: NOOP
  healthCheckRestClientParameters:
    - clientName: api
      hostname: localhost
      port: 6968
      userName: policyadmin
      password: zb!XztG34
      useHttps: false
      basePath: policy/api/v1/healthcheck
    - clientName: distribution
      hostname: policy-distribution
      port: 6969
      userName: healthcheck
      password: zb!XztG34
      useHttps: true
      basePath: healthcheck
    - clientName: kafka
      hostname: kafka
      port: 3905
      useHttps: true
      basePath: topics

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
      path-mapping:
        -metrics: plain-metrics
        -prometheus: metrics
