
participant:
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c01
    clampAutomationCompositionTopics:
      topicSources:
        - topic: policy-acruntime-participant
          servers:
            - ${topicServer:localhost:29092}
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
      topicSinks:
        - topic: policy-acruntime-participant
          servers:
            - ${topicServer:localhost:29092}
          topicCommInfrastructure: kafka
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.HttpAutomationCompositionElement
        typeVersion: 1.0.0

