
participant:
  localChartDirectory: /home/policy/local-charts
  infoFileName: CHART_INFO.json
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c02
    clampAutomationCompositionTopics:
      topicSources:
        -
          topic: policy-acruntime-participant
          servers:
            - ${topicServer:localhost:29092}
          topicCommInfrastructure: kafka
          fetchTimeout: 15000
      topicSinks:
        -
          topic: policy-acruntime-participant
          servers:
            - ${topicServer:localhost:29092}
          topicCommInfrastructure: kafka
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.K8SMicroserviceAutomationCompositionElement
        typeVersion: 1.0.0
