
runtime:
  topics:
    operationTopic: policy-acruntime-participant
    syncTopic: acm-ppnt-sync
  participantParameters:
    heartBeatMs: 20000
    maxStatusWaitMs: 150000
    maxOperationWaitMs: 200000
  topicParameterGroup:
    topicSources:
      - topic: ${runtime.topics.operationTopic}
        servers:
          - localhost:29092
        topicCommInfrastructure: kafka
        fetchTimeout: 15000
    topicSinks:
      - topic: ${runtime.topics.operationTopic}
        servers:
          - localhost:29092
        topicCommInfrastructure: kafka
      - topic: ${runtime.topics.syncTopic}
        servers:
          - localhost:29092
        topicCommInfrastructure: kafka
  acmParameters:
    toscaElementName: org.onap.policy.clamp.acm.AutomationCompositionElement
    toscaCompositionName: org.onap.policy.clamp.acm.AutomationComposition
